In [13]:
import torch


def empty_slicer(t):
    return [slice(None) for _ in t.shape]


def slice_tensor(t, start, end, dim):
    s = empty_slicer(t)
    s[dim] = slice(start, end)
    return t[tuple(s)]


t = torch.arange(24).reshape(2, 3, 4)
print(t)
print(slice_tensor(t, 1, 3, 1))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [19]:
t = torch.arange(12).reshape(3,4)
row_idx = [0,1]
col_idx = [2,3]
print(t)
print(t[row_idx, col_idx])
print(t[0:1, 2:3])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([2, 7])
tensor([[2]])
